// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMedicao;

namespace Medição.Migrations
{
    [DbContext(typeof(MedicaoDbContext))]
    [Migration("20200728181039_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaMedicao.Models.Medicao", b =>
                {
                    b.Property<int>("IdMedicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PessoaIdpessoa")
                        .HasColumnType("int");

                    b.Property<float>("Temperatura")
                        .HasColumnType("real");

                    b.HasKey("IdMedicao");

                    b.HasIndex("PessoaIdpessoa");

                    b.ToTable("Medicoes");
                });

            modelBuilder.Entity("SistemaMedicao.Models.Pessoa", b =>
                {
                    b.Property<int>("Idpessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("SetorIdSetor")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Idpessoa");

                    b.HasIndex("SetorIdSetor");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("SistemaMedicao.Models.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdSetor");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("SistemaMedicao.Models.Medicao", b =>
                {
                    b.HasOne("SistemaMedicao.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaIdpessoa");
                });

            modelBuilder.Entity("SistemaMedicao.Models.Pessoa", b =>
                {
                    b.HasOne("SistemaMedicao.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorIdSetor");
                });
#pragma warning restore 612, 618
        }
    }
}
